language: cpp

before_install:
- cat build.config
- X_EMAIL=$(grep -E 'email=(.*)' build.config | cut -c 7-)
- X_BRANCH=$(grep -E 'branch=(.*)' build.config | cut -c 8-)
- X_MODULES=$(grep -E 'modules=(.*)' build.config | cut -c 9-)
- X_U8G_FONTS=$(grep -E 'u8g-fonts=(.*)' build.config | cut -c 11-)
- X_SSL_ENABLED=$(grep -E 'ssl-enabled=(.*)' build.config | cut -c 12-)
# count ',' in the string and add +1
- X_NUMBER_OF_MODULES=$((`echo $X_MODULES | tr -d -c ',' | wc -m`+1))

- curl 'http://frightanic.com/nodemcu-custom-build/hook.php?event=start&recipient='$X_EMAIL
- git clone --depth=50 --branch=$X_BRANCH git://github.com/nodemcu/nodemcu-firmware.git nodemcu-firmware

# dig in and modify those config files
- cd nodemcu-firmware/app/include

# replace ',' by newline, make it uppercase and prepend every item with '#define LUA_USE_MODULES_'
- export X_MODULES_STRING=$(echo $X_MODULES | tr , '\n' | tr '[a-z]' '[A-Z]' | perl -pe 's/(.*)\n/#define LUA_USE_MODULES_$1\n/g')
# inject the modules string into user_modules.h between '#ifdef LUA_USE_MODULES\n' and '\n#endif /* LUA_USE_MODULES */'
# the 's' flag in '/sg' makes . match newlines
# Perl creates a temp file which is removed right after the manipulation
- perl -e 'local $/; $_ = <>; s/(#ifdef LUA_USE_MODULES\n)(.*)(\n#endif \/\* LUA_USE_MODULES \*\/)/$1$ENV{"X_MODULES_STRING"}$3/sg; print' user_modules.h > user_modules.h.tmp && mv user_modules.h.tmp user_modules.h

# comment the SSL flag if not enabled
- [ "${X_SSL_ENABLED}" != "true" ] && sed -e 's/#define CLIENT_SSL_ENABLE/\/\/ #define CLIENT_SSL_ENABLE/g' user_config.h > user_config.h.tmp && mv user_config.h.tmp user_config.h

# replace ',' by newline and turn every item into '    U8G_FONT_TABLE_ENTRY(<font-name>) \'
- export X_U8G_FONTS_STRING=$(echo -n X_U8G_FONTS | tr , '\n' | perl -pe 's/(.*)\n/    U8G_FONT_TABLE_ENTRY($1) \\\n/g')
# inject the fonts string into u8g_config.h between '#define U8G_FONT_TABLE \\n' and '\n#undef U8G_FONT_TABLE_ENTRY'
# the 's' flag in '/sg' makes . match newlines
# Perl creates a temp file which is removed right after the manipulation
- perl -e 'local $/; $_ = <>; s/(#define U8G_FONT_TABLE \\\n)(.*)(\n#undef U8G_FONT_TABLE_ENTRY)/$1$ENV{"X_U8G_FONTS_STRING"}$3/sg; print' u8g_config.h > u8g_config.h.tmp && mv u8g_config.h.tmp u8g_config.h

- cat user_modules.h
- cat user_config.h
- cat u8g_config.h
# back to where we came from
- cd $TRAVIS_BUILD_DIR

- cd nodemcu-firmware
- ls -altr
- sudo apt-get install -y python-serial srecord

install:
- wget https://github.com/GeorgeHahn/nodemcu-firmware/raw/travis/tools/esp-open-sdk.tar.gz -O tools/esp-open-sdk.tar.gz
- tar -zxvf tools/esp-open-sdk.tar.gz
- export PATH=$PATH:$PWD/esp-open-sdk/sdk:$PWD/esp-open-sdk/xtensa-lx106-elf/bin
script:
- make all
- cd bin/
- timestamp=$(date "+%Y-%m-%d-%H-%M-%S")
- base_file_name="nodemcu-"$X_BRANCH"-"$X_NUMBER_OF_MODULES"-modules-"$timestamp
- file_name_float=$base_file_name"-float.bin"
- srec_cat  -output ${file_name_float} -binary 0x00000.bin -binary -fill 0xff 0x00000 0x10000 0x10000.bin -binary -offset 0x10000
- cd ../
- make clean
- make EXTRA_CCFLAGS="-DLUA_NUMBER_INTEGRAL"
- cd bin/
- file_name_integer=$base_file_name"-integer.bin"
- srec_cat -output ${file_name_integer} -binary 0x00000.bin -binary -fill 0xff 0x00000 0x10000 0x10000.bin -binary -offset 0x10000

after_success:
- cd $TRAVIS_BUILD_DIR
- pwd
- cp "$TRAVIS_BUILD_DIR/nodemcu-firmware/bin/${file_name_float}" .
- cp "$TRAVIS_BUILD_DIR/nodemcu-firmware/bin/${file_name_integer}" .
- rm -fr "$TRAVIS_BUILD_DIR/nodemcu-firmware"
- ls -al
- curl -T "{${file_name_float},${file_name_integer}}" -u ${FTP_USER}:${FTP_PASSWORD} --ftp-ssl -k ftp://82.195.224.128
- curl 'http://frightanic.com/nodemcu-custom-build/hook.php?event=success&recipient='$X_EMAIL'&branch='$X_BRANCH'&modules='$X_MODULES'&artifacts='${file_name_float},${file_name_integer}

env:
  global:
    secure: "r3EKLjmOgWJzTECiTzPvE4Cz/QrO1Ll0ToeXAX2Lf/4BCBDL6V3cUUaQkXJAFKLiSxDIKb+sXYm3k/0JoSv5/ljlIoz1HJOAgwcNaM+dAfhI0/rS7RqZueSeK+F+UhfJ5CsN5hd+GvQ8bIT5+mXmU+ssL7RsJEx7YFvFtlrmosY="

notifications:
  email:
    recipients:
      - nodemcu-custom-build@frightanic.com
    on_success: never
    on_failure: always
  webhooks:
      urls:
        - http://frightanic.com/nodemcu-custom-build/hook.php?event=failure&recipient=$X_EMAIL
      on_success: never
      on_failure: always
      on_start: never

#branches:
 # only:
  #  - builds
  #  - testing
