language: cpp

before_install:
- git clone --depth=50 --branch=master git://github.com/nodemcu/nodemcu-firmware.git nodemcu-firmware
# copy the custom NodeMCU modules config to the cloned repo
- cp -R app nodemcu-firmware/
- cat nodemcu-firmware/app/include/user_modules.h
- cd nodemcu-firmware
- ls -altr
- sudo apt-get install -y python-serial srecord

install:
- wget https://github.com/GeorgeHahn/nodemcu-firmware/raw/travis/tools/esp-open-sdk.tar.gz -O tools/esp-open-sdk.tar.gz
- tar -zxvf tools/esp-open-sdk.tar.gz
- export PATH=$PATH:$PWD/esp-open-sdk/sdk:$PWD/esp-open-sdk/xtensa-lx106-elf/bin
script:
- make all
- cd bin/
- file_name_float="nodemcu_float.bin"
- srec_cat  -output ${file_name_float} -binary 0x00000.bin -binary -fill 0xff 0x00000 0x10000 0x10000.bin -binary -offset 0x10000
- cd ../
- make clean
- make EXTRA_CCFLAGS="-DLUA_NUMBER_INTEGRAL"
- cd bin/
- file_name_integer="nodemcu_integer.bin"
- srec_cat -output ${file_name_integer} -binary 0x00000.bin -binary -fill 0xff 0x00000 0x10000 0x10000.bin -binary -offset 0x10000

after_success:
- cd $TRAVIS_BUILD_DIR
- pwd
# copy NodeMCU binaries to root dir and delete the NodeMCU directory afterwards
- cp "$TRAVIS_BUILD_DIR/nodemcu-firmware/bin/${file_name_float}" .
- cp "$TRAVIS_BUILD_DIR/nodemcu-firmware/bin/${file_name_integer}" .
- rm -fr "$TRAVIS_BUILD_DIR/nodemcu-firmware"
- ls -al
- git config user.name "${GIT_NAME}"
- git config user.email "${GIT_EMAIL}"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
# re-attach branch that was detached sometime during the build ('git clone' of the nodemcu repo?)
- git checkout $TRAVIS_BRANCH
- git add ${file_name_float} ${file_name_integer}
- git commit -m "Add compiled NodeMCU firmware binaries"
- git status
# Travis uses git://<repo> to checkout but you can't push to git:// resources
- git push https://github.com/marcelstoer/nodemcu-custom-build.git

env:
  global:
    secure: "AZIj7u86av/GfbAQO2ln/3302vPQYLa2AdusPHZA0slVtHWMK/q8TZcqDwx6U49/ps/z5d7dc6Py4L9NgmiXx9PE6846RTM1OTqOWvE/Aw8Ome2Cs7sCnlzpPUvH6VIufqqa0jHgBjWv1YL1yEZufSjVl/Ih+sypSLl03GJ+uII="
